# Generated by Django 2.2.4 on 2019-08-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
