# Generated by Django 2.2.3 on 2019-08-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
